add c3pm binary installation doc
c3pm-labs/docs pull request #11
Opened 2021-03-16 16:09 UTC by Codelax

- [x] Linux
- [x] Macos
- [ ] Windows

2021-04-13 16:50 UTC, chloe-opteameo commented on docs/getting_started/install.md
> +No c++ compiler is being installed alongside c3pm, this is left to user
```suggestion
No c++ compiler is being installed alongside c3pm, this is left to the user
```

2021-04-13 16:50 UTC, chloe-opteameo commented on docs/getting_started/install.md
> +Before c3pm, you should install cmake and a c++ compiler
```suggestion
Before installing c3pm, you should install CMake and a c++ compiler
```

2021-04-13 16:50 UTC, chloe-opteameo commented on docs/getting_started/install.md
> +C3PM provide a tap to install and update it easily
```suggestion
C3PM provides a tap to install and update it easily
```

2021-04-13 16:50 UTC, chloe-opteameo commented on docs/getting_started/install.md
> +Installation of cmake and a c++ compiler is left to user.
```suggestion
Installation of CMake and a c++ compiler is left to the user.
```

2021-08-22 16:08 UTC, angela-boyadjian requested changes

2021-08-22 16:08 UTC, angela-boyadjian commented on docs/getting_started/install.md
> +We do not yet have repositories to easily install c3pm on windows.
Windows instead of windows

2021-08-31 08:42 UTC, chloebourbion commented on docs/getting_started/install.md
> +We do not yet have repositories to easily install c3pm on windows.
```suggestion
We do not yet have repositories to easily install c3pm on Windows.
```

2021-08-31 08:42 UTC, chloebourbion approved these changes

2021-08-31 08:45 UTC, chloebourbion approved these changes

2021-09-16 13:25 UTC, angela-boyadjian approved these changes

2021-09-16 13:25 UTC, merged